<?php

namespace Tests\Feature;

use App\Models\Competition;
use App\Models\CupTie;
use App\Models\Game;
use App\Models\GameMatch;
use App\Models\GameStanding;
use App\Models\Team;
use App\Models\User;
use App\Modules\Match\Handlers\SwissFormatHandler;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * The European half of the draw ceremony.
 *
 * UCL/UEL/UECL knockout rounds are generated by SwissFormatHandler rather than
 * CupDrawService, so this path has no drawn Collection to inspect and needs its
 * own coverage: the hook lives at the end of generateKnockoutRound(), which every
 * Swiss round funnels through.
 */
class SwissDrawRevealTest extends TestCase
{
    use RefreshDatabase;

    private Game $game;
    private Competition $competition;
    private Team $userTeam;

    /** @var array<int, Team> league position (1..36) => Team */
    private array $teamsByPosition = [];

    protected function setUp(): void
    {
        parent::setUp();

        $this->competition = Competition::factory()->create([
            'id' => 'UCL',
            'handler_type' => 'swiss_format',
            'season' => '2025',
        ]);

        $this->userTeam = Team::factory()->create();

        $this->game = Game::factory()->create([
            'user_id' => User::factory()->create()->id,
            'team_id' => $this->userTeam->id,
            'season' => '2025',
            'base_season' => '2025',
        ]);
    }

    /**
     * Seed a finished league phase, planting the user's team at $userPosition.
     * Positions 9-24 go into the knockout playoff; 1-8 skip it for the R16.
     */
    private function seedStandings(int $userPosition): void
    {
        for ($pos = 1; $pos <= 36; $pos++) {
            $team = $pos === $userPosition ? $this->userTeam : Team::factory()->create();
            $this->teamsByPosition[$pos] = $team;

            GameStanding::create([
                'game_id' => $this->game->id,
                'competition_id' => $this->competition->id,
                'team_id' => $team->id,
                'position' => $pos,
                'played' => 8,
                'won' => 0,
                'drawn' => 0,
                'lost' => 0,
                'goals_for' => 0,
                'goals_against' => 0,
                'points' => max(0, 36 - $pos),
            ]);
        }
    }

    private function generatePlayoffRound(): void
    {
        // beforeMatches only looks at competitions the game actually has matches
        // for. One played league fixture is enough to make the competition real
        // and leave the league phase reading as complete.
        GameMatch::factory()->create([
            'game_id' => $this->game->id,
            'competition_id' => $this->competition->id,
            'home_team_id' => $this->teamsByPosition[1]->id,
            'away_team_id' => $this->teamsByPosition[2]->id,
            'played' => true,
            'cup_tie_id' => null,
        ]);

        app(SwissFormatHandler::class)->beforeMatches($this->game, '2026-02-17');
    }

    public function test_queues_the_ceremony_when_the_user_is_drawn_into_the_playoff(): void
    {
        $this->seedStandings(userPosition: 9);

        $this->generatePlayoffRound();

        $this->assertSame(8, CupTie::where('game_id', $this->game->id)
            ->where('competition_id', 'UCL')
            ->where('round_number', 1)
            ->count());

        $this->assertSame(
            [['competition_id' => 'UCL', 'round' => 1]],
            $this->game->fresh()->pending_draw_reveal
        );
    }

    public function test_does_not_queue_the_playoff_for_a_team_that_skipped_it(): void
    {
        // Top eight go straight to the last 16 — the playoff draw is not theirs.
        $this->seedStandings(userPosition: 1);

        $this->generatePlayoffRound();

        $this->assertSame(8, CupTie::where('game_id', $this->game->id)
            ->where('competition_id', 'UCL')
            ->where('round_number', 1)
            ->count());

        $this->assertNull($this->game->fresh()->pending_draw_reveal);
    }
}
