<?php

namespace App\Modules\Academy\Services;

use App\Modules\Squad\Configs\TeamRegionalOrigins;
use App\Modules\Squad\DTOs\GeneratedPlayerData;
use App\Models\AcademyPlayer;
use App\Models\Game;
use App\Models\GamePlayer;
use App\Modules\Player\PlayerAge;
use Illuminate\Support\Collection;
use Illuminate\Support\Str;
use App\Modules\Player\Services\PlayerDevelopmentService;
use App\Modules\Player\Services\PlayerValuationService;
use App\Modules\Squad\Services\PlayerAttributeSampler;
use App\Modules\Squad\Services\PlayerGeneratorService;
use App\Modules\Squad\Services\SquadNumberService;

class YouthAcademyService
{
    /**
     * Tier configuration: [min_arrivals, max_arrivals]
     */
    private const TIER_CONFIG = [
        0 => [1, 1],
        1 => [2, 3],
        2 => [3, 5],
        3 => [4, 6],
        4 => [4, 6],
    ];

    /**
     * Base average ability for prospects generated by each academy tier.
     * Higher tiers produce better players on average.
     */
    private const ACADEMY_BASE_QUALITY = [
        0 => 38,   // Minimum: raw, unpolished prospect
        1 => 45,   // Basic: developing players
        2 => 52,   // Good: slightly above developing
        3 => 66,   // Elite: average-to-good
        4 => 74,   // World-Class: good, ready to contribute
    ];

    /**
     * Small adjustment to the ability mean based on first team's median tier.
     * Keeps academy output contextually anchored to club strength.
     */
    private const TEAM_CONTEXT_BONUS = [
        1 => -3,
        2 => -1,
        3 => 0,
        4 => 2,
        5 => 4,
    ];

    /**
     * Standard deviation for the ability normal distribution.
     * Uniform across all tiers — only the mean differentiates them.
     */
    private const ABILITY_STD_DEV = 6;

    private const ESTIMATED_MATCHDAYS = 38;

    /**
     * Season growth rates for development.
     * Controls what fraction of (potential - current) is gained per season.
     */
    private const GROWTH_RATE_ACADEMY = 0.25;
    private const GROWTH_RATE_LOAN = 0.35;

    /**
     * Position groups with weights for random selection.
     * First a group is chosen by weight, then a specific position within it.
     */
    private const POSITION_GROUPS = [
        ['weight' => 9,  'positions' => ['Goalkeeper']],
        ['weight' => 33, 'positions' => ['Centre-Back', 'Left-Back', 'Right-Back']],
        ['weight' => 29, 'positions' => ['Defensive Midfield', 'Central Midfield', 'Attacking Midfield']],
        ['weight' => 29, 'positions' => ['Left Winger', 'Right Winger', 'Centre-Forward']],
    ];

    public function __construct(
        private readonly PlayerGeneratorService $playerGenerator,
        private readonly SquadNumberService $squadNumberService,
        private readonly PlayerAttributeSampler $sampler,
        private readonly PlayerDevelopmentService $developmentService,
        private readonly PlayerValuationService $valuationService,
    ) {}

    /**
     * Roll for a single new academy prospect on one career-action tick.
     *
     * Prospects arrive year-round rather than in a season-start batch: each
     * tick we roll once with a per-tick probability calibrated so the expected
     * number of arrivals over a season matches the academy tier's average
     * (see perTickProspectProbability). On a hit, one prospect is generated.
     *
     * For filial games (clubs with a reserve team), the prospect is created as
     * a full GamePlayer on the reserve squad — no AcademyPlayer row. For
     * non-filial games, the prospect lands in the AcademyPlayer pool.
     *
     * @return AcademyPlayer|GamePlayer|null The new prospect, or null if none arrived this tick
     */
    public function maybeGenerateProspect(Game $game): AcademyPlayer|GamePlayer|null
    {
        $tier = $game->currentInvestment->youth_academy_tier ?? 0;

        $probability = self::perTickProspectProbability($tier);
        if (mt_rand(1, 10000) > (int) round($probability * 10000)) {
            return null;
        }

        $teamMedianTier = $this->getTeamMedianTier($game);
        $excludedNames = $this->getExistingPlayerNames($game);

        $traits = $this->rollProspectTraits($game, $tier, $teamMedianTier, $excludedNames);

        return $game->reserve_team_id !== null
            ? $this->persistAsReservePlayer($game, $traits)
            : $this->persistAsAcademyPlayer($game, $traits);
    }

    /**
     * Per-tick probability that a new prospect arrives, calibrated so the
     * expected season total equals the tier's average arrivals (mean of the
     * TIER_CONFIG min/max), spread across the ~38 ticks of a season.
     */
    public static function perTickProspectProbability(int $tier): float
    {
        $config = self::TIER_CONFIG[$tier] ?? self::TIER_CONFIG[0];
        $expectedSeasonArrivals = ($config[0] + $config[1]) / 2;

        return $expectedSeasonArrivals / self::ESTIMATED_MATCHDAYS;
    }

    /**
     * Develop all academy players' abilities for one matchday.
     * Growth is applied each matchday as a small increment toward potential.
     * Only non-loaned players develop (loaned develop at season end).
     */
    public function developPlayers(Game $game): void
    {
        $players = AcademyPlayer::where('game_id', $game->id)
            ->where('team_id', $game->team_id)
            ->where('is_on_loan', false)
            ->get();

        if ($players->isEmpty()) {
            return;
        }

        // Compute growth in memory, batch update changed players in a single query
        $updates = []; // [id => overall_score]
        foreach ($players as $player) {
            $computed = $this->computeGrowth($player, self::GROWTH_RATE_ACADEMY);
            if ($computed !== null) {
                $updates[$player->id] = $computed;
            }
        }

        if (! empty($updates)) {
            $this->bulkUpdateAbilities($updates);
        }
    }

    /**
     * Compute one matchday of growth for a player (pure calculation, no DB).
     *
     * @return int|null New overall_score, or null if unchanged
     */
    private function computeGrowth(AcademyPlayer $player, float $seasonRate): ?int
    {
        $growth = max(0, ($player->potential - $player->overall_score) * $seasonRate / self::ESTIMATED_MATCHDAYS);
        $newOverall = (int) round(min($player->potential, $player->overall_score + $growth));

        if ($newOverall === $player->overall_score) {
            return null;
        }

        return $newOverall;
    }

    /**
     * Bulk update abilities using CASE WHEN (1 query instead of N).
     *
     * @param  array<string, int>  $updates  [id => new overall_score]
     */
    private function bulkUpdateAbilities(array $updates): void
    {
        $ids = array_keys($updates);
        $idList = "'" . implode("','", $ids) . "'";

        $cases = [];
        foreach ($updates as $id => $value) {
            $cases[] = "WHEN id = '{$id}' THEN {$value}";
        }

        \Illuminate\Support\Facades\DB::statement("
            UPDATE academy_players
            SET overall_score = CASE " . implode(' ', $cases) . " ELSE overall_score END
            WHERE id IN ({$idList})
        ");
    }

    /**
     * Apply a full season of off-screen development to loaned players.
     * Called at season end when loans return.
     */
    public function developLoanedPlayers(Game $game): void
    {
        $loanedPlayers = AcademyPlayer::where('game_id', $game->id)
            ->where('team_id', $game->team_id)
            ->where('is_on_loan', true)
            ->get();

        foreach ($loanedPlayers as $player) {
            // Apply full season growth at loan rate
            $growth = ($player->potential - $player->overall_score) * self::GROWTH_RATE_LOAN;

            $player->update([
                'overall_score' => min($player->potential, (int) round($player->overall_score + $growth)),
            ]);
        }
    }

    /**
     * Return all loaned players to the academy at season end.
     *
     * @return Collection<int, AcademyPlayer> The returned players
     */
    public function returnLoans(Game $game): Collection
    {
        $loanedPlayers = AcademyPlayer::where('game_id', $game->id)
            ->where('team_id', $game->team_id)
            ->where('is_on_loan', true)
            ->get();

        foreach ($loanedPlayers as $player) {
            $player->update(['is_on_loan' => false]);
        }

        return $loanedPlayers;
    }

    /**
     * Mark a player as loaned out.
     */
    public function loanPlayer(AcademyPlayer $player): void
    {
        $player->update(['is_on_loan' => true]);
    }

    /**
     * Dismiss a player from the academy (permanently removed).
     */
    public function dismissPlayer(AcademyPlayer $player): void
    {
        $player->delete();
    }

    /**
     * Promote an academy player to the first team.
     * Creates Player + GamePlayer records and deletes the AcademyPlayer.
     */
    public function promoteToFirstTeam(AcademyPlayer $academy, Game $game): GamePlayer
    {
        $gamePlayer = $this->playerGenerator->create($game, new GeneratedPlayerData(
            teamId: $academy->team_id,
            position: $academy->position,
            overallScore: $academy->overall_score,
            dateOfBirth: $academy->date_of_birth,
            contractYears: 2,
            name: $academy->name,
            nationality: $academy->nationality,
            potential: $academy->potential,
            potentialLow: $academy->potential_low,
            potentialHigh: $academy->potential_high,
            fitnessMin: 85,
            fitnessMax: 100,
            moraleMin: 70,
            moraleMax: 90,
            joinedFrom: \App\Models\UserSquadCareerRecord::ORIGIN_ACADEMY,
        ));

        $gamePlayer->update([
            'number' => $this->squadNumberService->assignNumberForNewPlayer($game, $gamePlayer),
        ]);

        $academy->delete();

        return $gamePlayer;
    }

    /**
     * Auto-promote all academy players who have reached ACADEMY_END age.
     *
     * @return Collection<int, GamePlayer> The promoted players
     */
    public function promoteOveragePlayers(Game $game): Collection
    {
        if (! $game->current_date) {
            return collect();
        }

        $cutoff = PlayerAge::dateOfBirthCutoff(PlayerAge::ACADEMY_END, $game->current_date);

        $overagePlayers = AcademyPlayer::where('game_id', $game->id)
            ->where('team_id', $game->team_id)
            ->where('date_of_birth', '<=', $cutoff)
            ->get();

        return $overagePlayers->map(fn (AcademyPlayer $academy) => $this->promoteToFirstTeam($academy, $game));
    }

    /**
     * Promote the N highest-potential non-loaned academy players to the first team.
     *
     * @return Collection<int, GamePlayer> The promoted players
     */
    public function promoteBestPlayers(Game $game, int $count): Collection
    {
        if ($count <= 0) {
            return collect();
        }

        $candidates = AcademyPlayer::where('game_id', $game->id)
            ->where('team_id', $game->team_id)
            ->where('is_on_loan', false)
            ->orderByDesc('potential')
            ->limit($count)
            ->get();

        return $candidates->map(fn (AcademyPlayer $academy) => $this->promoteToFirstTeam($academy, $game));
    }

    /**
     * Get the expected new arrivals range for a tier.
     *
     * @return array{min: int, max: int}
     */
    public static function getArrivalsRange(int $tier): array
    {
        $config = self::TIER_CONFIG[$tier] ?? self::TIER_CONFIG[0];

        return ['min' => $config[0], 'max' => $config[1]];
    }

    public static function getTierDescription(int $tier): string
    {
        return __('squad.academy_tier_'.(match ($tier) {
            0, 1, 2, 3, 4 => $tier,
            default => 'unknown',
        }));
    }

    public static function getProspectInfo(int $tier): array
    {
        $config = self::TIER_CONFIG[$tier] ?? self::TIER_CONFIG[0];

        return [
            'min_prospects' => $config[0],
            'max_prospects' => $config[1],
        ];
    }

    /**
     * Teams whose academy only produces domestic players (cantera philosophy).
     * Maps team name → exact nationality filter (overrides weighted selection).
     */
    private const CANTERA_TEAMS = [
        'Athletic Club' => 'Spain',
    ];

    /**
     * Roll the shared traits for a youth prospect: position, age, abilities,
     * potential and identity. Quality follows a normal distribution centered
     * on the academy tier's base quality, adjusted by team context — this
     * produces realistic clustering with occasional gems and busts in the tails.
     *
     * The persistence target (AcademyPlayer pool vs reserve-squad GamePlayer)
     * is decided by the caller based on whether the game is filial.
     *
     * @param  array<int, string>  $excludedNames
     * @return array{
     *     position: string,
     *     age: int,
     *     dateOfBirth: \Carbon\Carbon,
     *     technical: int,
     *     physical: int,
     *     potential: int,
     *     potentialLow: int,
     *     potentialHigh: int,
     *     name: string,
     *     nationality: string,
     * }
     */
    private function rollProspectTraits(
        Game $game,
        int $academyTier,
        int $teamMedianTier,
        array $excludedNames,
    ): array {
        $position = $this->selectPosition();

        // Ability mean = academy base quality + team context bonus
        $abilityMean = self::ACADEMY_BASE_QUALITY[$academyTier] + self::TEAM_CONTEXT_BONUS[$teamMedianTier];

        $age = rand(17, 19);
        $ageCap = match ($age) {
            17 => 72,
            18 => 74,
            19 => 76,
            default => 78,
        };
        $overallScore = $this->sampler->sampleAbility($abilityMean, self::ABILITY_STD_DEV, 50, $ageCap);

        // Single potential pipeline: value the rolled prospect, then hand to
        // PlayerDevelopmentService so academy prospects follow the same logic
        // (incl. reachable cap) as every other player generated mid-game.
        $marketValue = $this->valuationService->overallScoreToMarketValue($overallScore, $age, null, $position);
        $potentialData = $this->developmentService->generatePotential($age, $overallScore, $marketValue);

        $dateOfBirth = $game->current_date->copy()->subYears($age)->subDays(rand(0, 364));

        $teamName = $game->team->name;
        $nationalityFilter = self::CANTERA_TEAMS[$teamName] ?? null;
        $teamCountry = $nationalityFilter ? null : $game->team->country;
        // Basque / Catalan clubs draw on custom Faker providers instead of es_ES
        // so their canteranos get regional names (Etxeberria, Fàbregas, …).
        $region = TeamRegionalOrigins::regionFor($teamName);
        $identity = $this->playerGenerator->pickRandomIdentity(
            $nationalityFilter,
            $teamCountry,
            $excludedNames,
            $region,
        );

        return [
            'position' => $position,
            'age' => $age,
            'dateOfBirth' => $dateOfBirth,
            'overallScore' => $overallScore,
            'potential' => $potentialData['potential'],
            'potentialLow' => $potentialData['low'],
            'potentialHigh' => $potentialData['high'],
            'name' => $identity['name'],
            'nationality' => $identity['nationality'],
        ];
    }

    /**
     * Persist a rolled prospect as an AcademyPlayer pool entry (non-filial games).
     *
     * @param  array<string, mixed>  $traits
     */
    private function persistAsAcademyPlayer(Game $game, array $traits): AcademyPlayer
    {
        return AcademyPlayer::create([
            'id' => Str::uuid()->toString(),
            'game_id' => $game->id,
            'team_id' => $game->team_id,
            'name' => $traits['name'],
            'nationality' => $traits['nationality'],
            'date_of_birth' => $traits['dateOfBirth'],
            'position' => $traits['position'],
            'overall_score' => $traits['overallScore'],
            'potential' => $traits['potential'],
            'potential_low' => $traits['potentialLow'],
            'potential_high' => $traits['potentialHigh'],
            'appeared_at' => $game->current_date,
            'is_on_loan' => false,
            'joined_season' => (int) $game->season,
            'initial_overall' => $traits['overallScore'],
        ]);
    }

    /**
     * Persist a rolled prospect as a full GamePlayer on the reserve squad
     * (filial games). The reserve squad is the source of truth for filial
     * players, so prospects skip the AcademyPlayer pool entirely.
     *
     * @param  array<string, mixed>  $traits
     */
    private function persistAsReservePlayer(Game $game, array $traits): GamePlayer
    {
        return $this->playerGenerator->create($game, new GeneratedPlayerData(
            teamId: $game->reserve_team_id,
            position: $traits['position'],
            overallScore: $traits['overallScore'],
            dateOfBirth: $traits['dateOfBirth'],
            contractYears: 2,
            name: $traits['name'],
            nationality: $traits['nationality'],
            potential: $traits['potential'],
            potentialLow: $traits['potentialLow'],
            potentialHigh: $traits['potentialHigh'],
            fitnessMin: 85,
            fitnessMax: 100,
            moraleMin: 70,
            moraleMax: 90,
            joinedFrom: \App\Models\UserSquadCareerRecord::ORIGIN_ACADEMY,
        ));
    }

    /**
     * Get the median PlayerTier of the first team's squad.
     */
    private function getTeamMedianTier(Game $game): int
    {
        $tiers = GamePlayer::where('game_id', $game->id)
            ->where('team_id', $game->team_id)
            ->pluck('tier')
            ->sort()
            ->values();

        if ($tiers->isEmpty()) {
            return 2; // fallback for empty squads
        }

        $midIndex = intdiv($tiers->count(), 2);

        return $tiers[$midIndex];
    }

    /**
     * Get names of every existing player in the game — all first-team squads
     * (any team, plus free agents) and all academy rosters. Game-wide scope is
     * required so that a new canterano's name doesn't collide with a player on
     * another team (issue #819).
     *
     * @return string[]
     */
    private function getExistingPlayerNames(Game $game): array
    {
        $playerNames = GamePlayer::where('game_id', $game->id)
            ->pluck('name')
            ->toArray();

        $academyNames = AcademyPlayer::where('game_id', $game->id)
            ->pluck('name')
            ->toArray();

        return array_merge($playerNames, $academyNames);
    }

    private function selectPosition(): string
    {
        $random = rand(1, 100);

        foreach (self::POSITION_GROUPS as $group) {
            $random -= $group['weight'];
            if ($random <= 0) {
                return $group['positions'][array_rand($group['positions'])];
            }
        }

        return 'Central Midfield';
    }
}
