<?php

namespace App\Modules\Match\Support;

use Illuminate\Support\Collection;

/**
 * Compute stoppage durations from the match's actual event mix instead of
 * sampling blindly.
 *
 * Approximates the IFAB-style accounting the referee does on the touchline:
 *
 *     baseline + N seconds per substitution + N per card + N per injury + N per goal
 *
 * with two safety constraints:
 *
 *   - Stoppage must be at least long enough to fit the latest event placed
 *     in that half by the simulator (no events past the configured window).
 *   - Clamped to a sane minimum (1 min) and maximum (configurable, default 12).
 */
final class StoppageCalculator
{
    /**
     * Accepts either a Collection of MatchEventData objects (from
     * MatchSimulator) or a list of array rows (from AIMatchResolver).
     * Both shapes carry `minute` and a type field — we normalise here
     * so callers don't have to convert.
     *
     * @param  Collection|iterable  $events  Events with raw absolute minutes.
     * @return array{first_half:int, second_half:int}
     */
    public function calculateRegulation($events): array
    {
        $events = $events instanceof Collection ? $events : collect($events);

        return [
            'first_half' => $this->calculateForHalf($events, periodEnd: 45, isFirstHalf: true),
            'second_half' => $this->calculateForHalf($events, periodEnd: 90, isFirstHalf: false),
        ];
    }

    /**
     * Compute ET stoppage. The simulator's ET range may extend a few minutes
     * past the nominal 120th, so etshs needs to accommodate any generated
     * events. ET 1H stoppage is rare in real football — we assign all ET
     * stoppage to the second half for simplicity (etfhs = 0).
     *
     * @param  Collection|iterable  $events  ET events only.
     * @param  int  $regulationStoppage  Total persisted regulation stoppage
     *                                   (first + second half). ET 2H ends at
     *                                   raw minute (120 + regulationStoppage).
     *                                   Both halves are required: omitting the
     *                                   first-half value pulls the boundary
     *                                   into ET 2H and inflates the overflow
     *                                   estimate.
     * @return array{et_first_half:int, et_second_half:int}
     */
    public function calculateExtraTime($events, int $regulationStoppage = 0): array
    {
        $events = $events instanceof Collection ? $events : collect($events);

        $cfg = $this->config();
        $maxEt = (int) ($cfg['et_max_minutes'] ?? 4);
        $etSecondHalfEnd = 120 + $regulationStoppage;

        // ET 2H spans absolute minutes (105+regStoppage+1) .. etSecondHalfEnd.
        // For simplicity count all ET events together — the formula is
        // dominated by total event count, not the per-half split.
        $subs = $this->countByType($events, ['substitution']);
        $cards = $this->countByType($events, ['yellow_card', 'red_card']);
        $injuries = $this->countByType($events, ['injury']);
        $goals = $this->countByType($events, ['goal', 'own_goal']);

        $totalSeconds = $cfg['baseline_seconds']
            + $cfg['seconds_per_substitution'] * $subs
            + $cfg['seconds_per_card'] * $cards
            + $cfg['seconds_per_injury'] * $injuries
            + $cfg['seconds_per_goal'] * $goals;

        $formulaMinutes = (int) ceil($totalSeconds / 60);

        // Ensure etshs is at least large enough to hold any event the
        // simulator placed past nominal ET end — otherwise the event would
        // fall outside the configured stoppage window during decomposition.
        $latest = $events->max(fn ($e) => $this->minuteOf($e)) ?? 0;
        $eventOverflow = max(0, $latest - $etSecondHalfEnd);

        return [
            'et_first_half' => 0,
            'et_second_half' => max(1, min($maxEt, max($formulaMinutes, $eventOverflow))),
        ];
    }

    private function calculateForHalf(Collection $events, int $periodEnd, bool $isFirstHalf): int
    {
        // Split events by half. First half = raw minute ≤ 45 (no 1H stoppage
        // generated by the simulator today). Second half = everything else
        // in the regulation range, including events the simulator placed in
        // stoppage minutes (raw 91+).
        $halfEvents = $isFirstHalf
            ? $events->filter(fn ($e) => $this->minuteOf($e) <= 45)
            : $events->filter(fn ($e) => $this->minuteOf($e) > 45);

        $subs = $this->countByType($halfEvents, ['substitution']);
        $cards = $this->countByType($halfEvents, ['yellow_card', 'red_card']);
        $injuries = $this->countByType($halfEvents, ['injury']);
        $goals = $this->countByType($halfEvents, ['goal', 'own_goal']);

        $cfg = $this->config();
        $totalSeconds = $cfg['baseline_seconds']
            + $cfg['seconds_per_substitution'] * $subs
            + $cfg['seconds_per_card'] * $cards
            + $cfg['seconds_per_injury'] * $injuries
            + $cfg['seconds_per_goal'] * $goals;

        $formulaMinutes = (int) ceil($totalSeconds / 60);

        // Ensure the stoppage window is long enough to hold the latest event
        // the simulator placed in this half — otherwise an event at raw 94
        // would decompose into ET territory instead of regulation stoppage.
        $eventOverflow = max(0, ($halfEvents->max(fn ($e) => $this->minuteOf($e)) ?? 0) - $periodEnd);

        $minMinutes = $isFirstHalf
            ? (int) ($cfg['first_half_min_minutes'] ?? 0)
            : (int) ($cfg['second_half_min_minutes'] ?? 1);
        $maxMinutes = (int) ($cfg['max_minutes'] ?? 12);

        return max($minMinutes, min($maxMinutes, max($formulaMinutes, $eventOverflow)));
    }

    /**
     * @param  Collection  $events
     * @param  list<string>  $types
     */
    private function countByType(Collection $events, array $types): int
    {
        return $events->filter(fn ($e) => in_array($this->typeOf($e), $types, true))->count();
    }

    private function typeOf(mixed $event): ?string
    {
        if (is_array($event)) {
            return $event['event_type'] ?? $event['type'] ?? null;
        }

        return $event->type ?? $event->event_type ?? null;
    }

    private function minuteOf(mixed $event): int
    {
        if (is_array($event)) {
            return (int) ($event['minute'] ?? 0);
        }

        return (int) ($event->minute ?? 0);
    }

    /**
     * @return array<string, int>
     */
    private function config(): array
    {
        return array_merge([
            'baseline_seconds' => 30,
            'seconds_per_substitution' => 30,
            'seconds_per_card' => 30,
            'seconds_per_injury' => 60,
            'seconds_per_goal' => 30,
            'first_half_min_minutes' => 0,
            'second_half_min_minutes' => 1,
            'max_minutes' => 12,
            'et_max_minutes' => 4,
        ], config('match_simulation.stoppage', []));
    }
}
