global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    server: virtua-fc-hetzner

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    static_configs:
      - targets: ['host.docker.internal:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: hetzner-host

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: postgres
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: redis
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: traefik
    static_configs:
      - targets: ['traefik:8082']
